### ISSUE TITLE
why do I have this error after starting the project?

### ISSUE THREAD

**Issue by gHashTag** [syfun/reader#1]
![simulator screen shot - iphone se - 2017-10-06 at 17 53 20](https://user-images.githubusercontent.com/6774813/31283814-58dd067a-aabf-11e7-98e6-343439284531.png)

**Comment by syfun** [comment]
@gHashTag Need upgrade expo and react-native, you can see these links.
[React Native 0.48 - `scrollview has no proptype for native Ask Question](https://stackoverflow.com/questions/46119806/react-native-0-48-scrollview-has-no-proptype-for-native)

[Expo SDK 21.0.0 is now available](https://blog.expo.io/expo-sdk-21-0-0-is-now-available-be33b79921b7)

**Comment by gHashTag** [comment]
I do not like expo )

**Comment by syfun** [comment]
@gHashTag Me too. This project was a simple demo for me, very simple. And now I go to swift....
